version: "3.7"
services:
  api:
    image: "golang:1.19-alpine"
    working_dir: /go/src/github.com/joesantos418/joe-chess
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src/github.com/joesantos418/joe-chess
    environment:
      LOG_HUMAN: "false"
    entrypoint:
      - go
      - run
      - ./cmd/api