package board

type Piece int64

const (
	NO_PIECE Piece = iota
	WHITE_PAWN_A
	WHITE_PAWN_B
	WHITE_PAWN_C
	WHITE_PAWN_D
	WHITE_PAWN_E
	WHITE_PAWN_F
	WHITE_PAWN_G
	WHITE_PAWN_H
	WHITE_ROOK_QUEEN
	WHITE_ROOK_KING
	WHITE_KNIGHT_QUEEN
	WHITE_KNIGHT_KING
	WHITE_BISHOP_QUEEN
	WHITE_BISHOP_KING
	WHITE_QUEEN
	WHITE_KING
	BLACK_PAWN_A
	BLACK_PAWN_B
	BLACK_PAWN_C
	BLACK_PAWN_D
	BLACK_PAWN_E
	BLACK_PAWN_F
	BLACK_PAWN_G
	BLACK_PAWN_H
	BLACK_ROOK_QUEEN
	BLACK_ROOK_KING
	BLACK_KNIGHT_QUEEN
	BLACK_KNIGHT_KING
	BLACK_BISHOP_QUEEN
	BLACK_BISHOP_KING
	BLACK_QUEEN
	BLACK_KING
)

func (p Piece) String() string {
	switch p {
	case NO_PIECE:
		return "NO_PIECE"
	case WHITE_PAWN_A:
		return "WHITE_PAWN_A"
	case WHITE_PAWN_B:
		return "WHITE_PAWN_B"
	case WHITE_PAWN_C:
		return "WHITE_PAWN_C"
	case WHITE_PAWN_D:
		return "WHITE_PAWN_D"
	case WHITE_PAWN_E:
		return "WHITE_PAWN_E"
	case WHITE_PAWN_F:
		return "WHITE_PAWN_F"
	case WHITE_PAWN_G:
		return "WHITE_PAWN_G"
	case WHITE_PAWN_H:
		return "WHITE_PAWN_H"
	case WHITE_ROOK_QUEEN:
		return "WHITE_ROOK_QUEEN"
	case WHITE_ROOK_KING:
		return "WHITE_ROOK_KING"
	case WHITE_KNIGHT_QUEEN:
		return "WHITE_KNIGHT_QUEEN"
	case WHITE_KNIGHT_KING:
		return "WHITE_KNIGHT_KING"
	case WHITE_BISHOP_QUEEN:
		return "WHITE_BISHOP_QUEEN"
	case WHITE_BISHOP_KING:
		return "WHITE_BISHOP_KING"
	case WHITE_QUEEN:
		return "WHITE_QUEEN"
	case WHITE_KING:
		return "WHITE_KING"
	case BLACK_PAWN_A:
		return "BLACK_PAWN_A"
	case BLACK_PAWN_B:
		return "BLACK_PAWN_B"
	case BLACK_PAWN_C:
		return "BLACK_PAWN_C"
	case BLACK_PAWN_D:
		return "BLACK_PAWN_D"
	case BLACK_PAWN_E:
		return "BLACK_PAWN_E"
	case BLACK_PAWN_F:
		return "BLACK_PAWN_F"
	case BLACK_PAWN_G:
		return "BLACK_PAWN_G"
	case BLACK_PAWN_H:
		return "BLACK_PAWN_H"
	case BLACK_ROOK_QUEEN:
		return "BLACK_ROOK_QUEEN"
	case BLACK_ROOK_KING:
		return "BLACK_ROOK_KING"
	case BLACK_KNIGHT_QUEEN:
		return "BLACK_KNIGHT_QUEEN"
	case BLACK_KNIGHT_KING:
		return "BLACK_KNIGHT_KING"
	case BLACK_BISHOP_QUEEN:
		return "BLACK_BISHOP_QUEEN"
	case BLACK_BISHOP_KING:
		return "BLACK_BISHOP_KING"
	case BLACK_QUEEN:
		return "BLACK_QUEEN"
	case BLACK_KING:
		return "BLACK_KING"
	}

	panic("unknow piece")
}
